algoritmo "semnome"
// Função : Calcular Valor para a compra do carro
// Autor :João Victor Morais
// Data : 12/03/2019
// Seção de Declarações 
var
 valorCar, resultadoImp, resultadoComis: real
inicio
escreval( "Digite o Valor do Carro")
leia(valorCar)
resultadoImp <- (valorCar*1.45)
resultadoComis <- (resultadoImp*1.28)
escreval( "O Preço do seu carro é R$:", resultadoComis)
escreval( "FIM")

fimalgoritmo
