algoritmo "Aula1Laço"
// Função : Todos os laços
// Autor : ojotav
// Data : 30/07/2019
// Seção de Declarações 
var
x: inteiro
inicio

escreval("----------LAÇO ENQUANTO----------")
x<-1
enquanto (x<=10) faca    //Espaço entre o enquanto e a expressão
escreval(x)
x<- x + 1 //Incremento
fimenquanto

escreval("----------LAÇO PARA----------")
x<-1
para x de 1 ate 10 faca
escreval(x)
fimpara

escreval("----------LAÇO REPITA----------")
x<-1
repita
escreval(x)
x<- x+1
ate (x>=11)



fimalgoritmo
